#theme: jekyll-theme-midnight
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme
title: Name James - meaning and history of given name James around the world
description: The meaning and history of given name James around the world
